# -*- coding: utf-8 -*-
"""boston.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F78X27DblYT4Dc_xYkrKcIA6hCXF9LVj
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from sklearn.datasets import load_boston
boston = load_boston()

df_x=pd.DataFrame(boston.data,columns=boston.feature_names)
df_y=pd.DataFrame(boston.target)

df_x.head()
df_x.tail()

reg = linear_model.LinearRegression()

X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=42)

reg.fit(X_train,y_train)

Y_pred=reg.predict(x_test)

plt.scatter(y_test,Y_pred)
plt.xlabel("prices")
plt.ylabel("predicted prices")
plt.show()

np.mean((a-y_test)**2)